packages:
  - 'apps/*'
  - 'packages/*'
allowBuilds:
  '@firebase/util': set this to true or false
  '@parcel/watcher': set this to true or false
  esbuild: set this to true or false
  protobufjs: set this to true or false
  vue-demi: set this to true or false
