name: Release Mobile App (Android)

on:
  release:
    types: [published]

jobs:
  build:
    name: Build Android APK
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node 24
        uses: actions/setup-node@v4
        with:
          node-version: 24

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9

      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: '17'

      - name: Get pnpm store directory
        id: pnpm-cache
        shell: bash
        run: |
          echo "STORE_PATH=$(pnpm store path)" >> $GITHUB_OUTPUT

      - name: Setup pnpm cache
        uses: actions/cache@v4
        with:
          path: ${{ steps.pnpm-cache.outputs.STORE_PATH }}
          key: ${{ runner.os }}-pnpm-store-${{ hashFiles('**/pnpm-lock.yaml') }}
          restore-keys: |
            ${{ runner.os }}-pnpm-store-

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build Web App
        run: pnpm --filter @nexus-notes/web generate

      - name: Add Android Platform
        run: pnpm --filter @nexus-notes/mobile exec cap add android

      - name: Build APK
        working-directory: apps/mobile/android
        run: ./gradlew assembleDebug # Cambiar a assembleRelease cuando se tengan llaves de firma

      - name: Upload APK to Release
        uses: softprops/action-gh-release@v1
        with:
          files: apps/mobile/android/app/build/outputs/apk/debug/app-debug.apk
